default: &default
  embedding_hidden: 256
  MLP_hidden: 256
  MLP_num_layers: 2
  dropout: 0.2
  lr: 1.0e-3
  wd: 0

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: false
  LearnMask: false
  PMA: true 
  heads: 8 
  output_heads: 1
  decoder_hidden: 64 
  decoder_num_layers: 2


cora: 
  <<: *default
  heads: 4

citeseer:
  <<: *default
  MLP_hidden: 512

'20newsW100':
  <<: *default

NTU2012:
  <<: *default
  heads: 1

house-committees-100:
  <<: *default
  heads: 1
  MLP_hidden: 512

pokec:
  <<: *default
